const { chromium } = require('playwright');
const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const C = require('../core.js');
const V = require('../vault.js');
const testPassword = 'Synthetic local password 2026';
const root = path.resolve(__dirname, '..');
const out = path.resolve(root, '..', 'qa');
const server = http.createServer(async (req, res) => {
  const file = path.resolve(root, '.' + decodeURIComponent(new URL(req.url, 'http://localhost').pathname === '/' ? '/index.html' : new URL(req.url, 'http://localhost').pathname));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403).end(); return; }
  try { const data = await fs.readFile(file); res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html'); res.end(data); }
  catch { res.writeHead(404).end(); }
});
async function main() {
  await fs.mkdir(out, { recursive: true });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || undefined, headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage(), errors = [];
  const remoteRequests = [];
  context.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith(url + '/')) remoteRequests.push(request.url()); });
  page.on('pageerror', error => errors.push(error.message));
  const click = name => page.getByRole('button', { name, exact: true }).click();
  const visible = async locator => { await locator.waitFor({ state: 'visible', timeout: 5000 }); assert.equal(await locator.isVisible(), true); };
  const hidden = async locator => { await locator.waitFor({ state: 'hidden', timeout: 5000 }); assert.equal(await locator.isVisible(), false); };
  const download = async (action, filename) => { const waiting = page.waitForEvent('download'); await action(); const file = await waiting; const target = path.join(out, filename); await file.saveAs(target); assert.equal(await file.failure(), null); return target; };
  const unlock = async (password = testPassword) => { await page.locator('#authForm [name=password]').fill(password); await page.locator('#authSubmit').click(); await visible(page.locator('#appShell')); };
  const backupPassword = async (password = testPassword) => { await page.locator('#passwordForm [name=password]').fill(password); await page.locator('#passwordForm').getByRole('button', { name: 'Continue' }).click(); };
  const injectPortfolio = async portfolio => {
    const encrypted = await V.create({ version: 1, profile: { name: 'QA profile' }, portfolio }, testPassword);
    await page.evaluate(data => localStorage.setItem('lendwiseVaultV1', JSON.stringify(data)), encrypted.record);
    await page.reload(); await unlock();
  };
  try {
    await page.goto(url);
    await page.screenshot({ path: path.join(out, 'paper-profile-desktop.png'), fullPage: true, animations: 'disabled' });
    await click('How your data is stored'); await visible(page.getByRole('heading', { name: 'How your data is stored', exact: true })); await page.locator('#utilityModal .close[data-close]').click();
    await hidden(page.locator('#appShell'));
    await page.locator('#authForm [name=profileName]').fill('QA profile');
    await page.locator('#authForm [name=password]').fill(testPassword);
    await page.locator('#authForm [name=confirmPassword]').fill(testPassword);
    await page.locator('#localConsentField input').check(); await page.locator('#authSubmit').click();
    await visible(page.locator('#appShell'));
    await visible(page.getByText('No borrowers yet. Add your first borrower to begin.'));
    // Close and cancel work even when required fields are empty. Escape restores focus.
    await page.locator('#newLoanTop').click();
    assert.equal(await page.locator('[name=phone]').getAttribute('placeholder'), null);
    await page.locator('#loanModal [data-close]').first().click(); await hidden(page.locator('#loanModal'));
    await page.locator('#newLoanHero').click(); await page.locator('#loanModal').getByRole('button', { name: 'Cancel' }).click();
    await page.locator('#addBorrower').click(); await page.keyboard.press('Escape'); await hidden(page.locator('#loanModal'));
    await page.locator('#addBorrower').click(); await page.locator('#loanForm [name=name]').fill('Unsaved entry'); await page.keyboard.press('Escape');
    await visible(page.getByRole('heading', { name: 'Discard unsaved changes?' })); await page.locator('#confirmModal').getByRole('button', { name: 'Cancel', exact: true }).click(); await visible(page.locator('#loanModal'));
    await page.locator('#loanModal .close').click(); await click('Discard changes'); await hidden(page.locator('#loanModal'));
    await visible(page.getByText('No borrowers yet. Add your first borrower to begin.'));
    await page.locator('#currencySelect').selectOption('INR');
    await page.locator('#addBorrower').click();
    const fields = page.locator('#loanForm');
    const name = 'Maya "Patel", 李 <b>';
    const firstDue = C.iso(new Date(new Date().getFullYear(), new Date().getMonth() - 2, 1, 12));
    for (const [key, value] of Object.entries({ name, phone: '+91 9000000000', amount: '1200', months: '3', rate: '0', firstDue, address: 'Test address', referrer: 'Test referrer', family: '+86 1000000000' })) await fields.locator(`[name="${key}"]`).fill(value);
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1kAAAAASUVORK5CYII=', 'base64');
    await fields.locator('[name=documents]').setInputFiles({ name: 'test-document.png', mimeType: 'image/png', buffer: png });
    await click('Save borrower & loan'); await hidden(page.locator('#loanModal'));
    assert.equal(await page.locator('#borrowerRows strong').first().textContent(), name);
    assert.equal(await page.locator('#borrowerRows b').count(), 0);
    assert.ok((await page.locator('#totalOutstanding').textContent()).includes('1,200'));
    await page.reload(); await hidden(page.locator('#appShell'));
    await page.locator('#authForm [name=password]').fill('wrong password'); await page.locator('#authSubmit').click(); await visible(page.locator('#authError')); await hidden(page.locator('#appShell'));
    await unlock(); await visible(page.getByText(name, { exact: true }).first());
    await page.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).click();
    assert.equal(await fields.locator('[name=phone]').inputValue(), '+91 9000000000');
    await fields.locator('[name=amount]').fill('1800'); await click('Save changes'); await hidden(page.locator('#loanModal'));
    assert.ok((await page.locator('#totalOutstanding').textContent()).includes('1,800'));
    await page.locator('#borrowerRows').getByRole('button', { name: 'Payments', exact: true }).click();
    assert.equal(await page.locator('#paymentRows tr').count(), 3);
    await page.locator('#paymentRows tr').first().getByRole('button').click();
    await click('Save payment'); await hidden(page.locator('#receiptModal'));
    assert.ok((await page.locator('#paymentRows tr').first().textContent()).includes('Paid late'));
    await page.locator('#paymentRows tr').nth(1).getByRole('button').click();
    await page.locator('#receiptForm [name=amount]').fill('100'); await click('Save payment'); await hidden(page.locator('#receiptModal'));
    assert.ok((await page.locator('#paymentRows tr').nth(1).textContent()).includes('Overdue (partial)'));
    assert.ok((await page.locator('#totalOutstanding').textContent()).includes('1,100'));
    assert.equal(await page.locator('#borrowerRows progress').getAttribute('value'), '39');
    await page.locator('#paymentStatusFilter').selectOption('paid'); assert.equal(await page.locator('#paymentRows tr').count(), 1);
    await page.locator('#paymentStatusFilter').selectOption('open'); assert.equal(await page.locator('#paymentRows tr').count(), 2);
    await page.locator('#paymentStatusFilter').selectOption('all');
    await page.screenshot({ path: path.join(out, 'repayments-desktop.png'), fullPage: true, animations: 'disabled' });
    await page.locator('#paymentsModal').getByRole('button', { name: 'Done', exact: true }).click();
    // Score is inspectable, read-only, escaped, current, and fits the phone layout.
    const expectedScore = C.repaymentScore({ amount: 1800, months: 3, rate: 0, firstDue, payments: { 1: { amount: 600, date: C.today() }, 2: { amount: 100, date: C.today() } } });
    const beforeScore = await page.evaluate(() => localStorage.getItem('lendwiseVaultV1'));
    await page.locator('#borrowerRows [data-action=score]').click(); await visible(page.locator('#scoreModal'));
    assert.equal(await page.locator('#scoreOverview .score-ring>span').textContent(), String(expectedScore.score));
    assert.equal(await page.locator('#scoreTitle').textContent(), `${name} — repayment score`); assert.equal(await page.locator('#scoreTitle b').count(), 0);
    await page.getByText('How this score works', { exact: true }).click(); await visible(page.getByText('100 points', { exact: true }));
    await page.getByText('View each scored installment', { exact: true }).click(); assert.equal(await page.locator('#scoreInstallments li').count(), expectedScore.assessed);
    await page.screenshot({ path: path.join(out, 'score-desktop.png'), animations: 'disabled' });
    for (const width of [320, 390]) {
      await page.setViewportSize({ width, height: 844 });
      assert.ok(await page.locator('#scoreModal').evaluate(element => element.scrollWidth <= element.clientWidth), `Score panel fits at ${width}px`);
    }
    await page.screenshot({ path: path.join(out, 'score-mobile.png'), animations: 'disabled' });
    await page.locator('#scoreModal [data-close]').first().click(); await hidden(page.locator('#scoreModal'));
    await page.setViewportSize({ width: 1440, height: 1000 });
    assert.equal(await page.evaluate(() => localStorage.getItem('lendwiseVaultV1')), beforeScore);
    await page.locator('#borrowerRows [data-action=score]').click(); await click('Open repayments');
    await page.locator('#paymentRows tr').nth(1).getByRole('button').click();
    await page.locator('#receiptForm [name=amount]').fill('200'); await click('Save payment'); await hidden(page.locator('#receiptModal'));
    const changedScore = C.repaymentScore({ amount: 1800, months: 3, rate: 0, firstDue, payments: { 1: { amount: 600, date: C.today() }, 2: { amount: 200, date: C.today() } } });
    assert.equal(await page.locator('#scoreOverview .score-ring>span').textContent(), String(changedScore.score));
    await page.locator('#paymentRows tr').nth(1).getByRole('button').click();
    await page.locator('#receiptForm [name=amount]').fill('100'); await click('Save payment'); await hidden(page.locator('#receiptModal'));
    await page.locator('#paymentsModal').getByRole('button', { name: 'Done', exact: true }).click();
    assert.equal(await page.locator('#scoreOverview .score-ring>span').textContent(), String(expectedScore.score));
    await page.keyboard.press('Escape'); await hidden(page.locator('#scoreModal'));
    // Terms with recorded money require confirmation and reject incompatible edits.
    await page.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).click();
    await fields.locator('[name=amount]').fill('300'); await click('Save changes'); await visible(page.locator('#loanError'));
    await fields.locator('[name=amount]').fill('1800'); await fields.locator('[name=firstDue]').fill(C.monthDate(firstDue, -1)); await click('Save changes');
    await visible(page.locator('#confirmModal')); await page.locator('#confirmModal').getByRole('button', { name: 'Cancel' }).click();
    await page.locator('#loanModal [data-close]').first().click();
    await click('Discard changes'); await hidden(page.locator('#loanModal'));
    await click('Review overdue loans ↗'); assert.equal(await page.locator('#statusFilter').inputValue(), 'overdue');
    await click('View active loans ↗'); assert.equal(await page.locator('#statusFilter').inputValue(), 'active'); await page.locator('#statusFilter').selectOption('all');
    // Search must accept ordinary phone formatting and multi-space/case name input.
    const beforeSearch = await page.evaluate(() => localStorage.getItem('lendwiseVaultV1'));
    for (const query of ['+91 (900) 000-0000', '   mAya    patel   ']) {
      await page.locator('#searchInput').fill(query);
      assert.ok((await page.locator('#borrowerRows').textContent()).includes(name), `Borrower found for ${query}`);
      assert.equal(await page.locator('#borrowersTitle').textContent(), 'Search results (1)');
      assert.ok(await page.locator('#borrowers').evaluate(element => element.getBoundingClientRect().top < document.querySelector('.hero-row').getBoundingClientRect().top), 'Results appear above the unchanged dashboard');
    }
    const searchUrl = page.url();
    await page.locator('#searchInput').press('Enter'); assert.equal(page.url(), searchUrl);
    assert.equal(await page.evaluate(() => document.activeElement.id), 'borrowers');
    await page.locator('#statusFilter').selectOption('paid');
    assert.ok((await page.locator('#searchFeedbackText').textContent()).includes('1 hidden by the status filter'));
    await click('Show all statuses'); await visible(page.locator('#borrowerRows').getByText(name, { exact: true }));
    await click('Clear search'); assert.equal(await page.locator('#searchInput').inputValue(), '');
    assert.equal(await page.locator('#borrowersTitle').textContent(), 'Borrowers');
    assert.equal(await page.evaluate(() => localStorage.getItem('lendwiseVaultV1')), beforeSearch);
    await page.locator('#searchInput').fill('missing name'); assert.ok((await page.locator('#borrowerRows').textContent()).includes('No borrowers match'));
    await page.locator('#searchInput').fill(''); await page.locator('#statusFilter').selectOption('paid'); assert.ok((await page.locator('#tableCount').textContent()).includes('0'));
    await page.locator('#statusFilter').selectOption('overdue'); await visible(page.locator('#borrowerRows').getByText(name, { exact: true }));
    await page.locator('#statusFilter').selectOption('all'); await page.locator('#sortSelect').selectOption('name');
    await page.locator('#chartPeriod').selectOption('12'); assert.equal(await page.locator('.bar-group').count(), 12);
    await page.locator('#notificationsBtn').click(); await visible(page.getByRole('heading', { name: 'Payment reminders' }));
    await page.locator('#remindersToggle').uncheck(); await page.locator('#utilityModal').getByRole('button', { name: 'Done', exact: true }).click();
    await page.getByRole('button', { name: 'Reminders', exact: false }).first().click(); assert.equal(await page.locator('#remindersToggle').isChecked(), false);
    await page.locator('#utilityModal .close[data-close]').click();
    await page.getByRole('button', { name: 'Documents', exact: true }).click();
    await download(() => click('Download'), 'document.png'); assert.deepEqual(await fs.readFile(path.join(out, 'document.png')), png);
    await page.locator('#utilityModal').getByRole('button', { name: 'Done', exact: true }).click();
    await page.locator('#exportBtn').click();
    const csvPath = await download(() => click('Download detailed CSV'), 'payments.csv');
    const csv = await fs.readFile(csvPath, 'utf8'); assert.ok(csv.includes('Overdue (partial)')); assert.ok(csv.includes('"INR"')); assert.ok(csv.includes('"\'+91 9000000000"'));
    const xlsxPath = await download(() => click('Download Excel (.xlsx)'), 'payments.xlsx');
    const Excel = require('../vendor/exceljs.min.js'), book = new Excel.Workbook(); await book.xlsx.load(await fs.readFile(xlsxPath));
    const sheet = book.worksheets[0]; assert.equal(sheet.rowCount, 4); assert.equal(sheet.getCell('T2').value, 'Paid late'); assert.equal(sheet.getCell('T2').font.color.argb, 'FF9C1C20'); assert.equal(sheet.getCell('P3').value, 100);
    assert.equal(sheet.getCell('X2').value, expectedScore.score); assert.equal(sheet.getCell('Y2').value, expectedScore.assessed); assert.equal(sheet.getCell('Z2').value, 'local-v1');
    await page.locator('#utilityModal .close[data-close]').click();
    await click('Settings & backup'); await page.locator('#settingsCurrency').selectOption('CNY'); assert.ok((await page.locator('#totalOutstanding').textContent()).includes('0.00'));
    await page.locator('#settingsCurrency').selectOption('INR');
    const backupPath = await download(() => click('Download encrypted backup'), 'portfolio.json');
    const rawBackup = await fs.readFile(backupPath, 'utf8');
    assert.equal(rawBackup.includes(name), false); assert.equal(rawBackup.includes('+91'), false); assert.equal(rawBackup.includes(testPassword), false);
    const decryptedBackup = await V.unlock(rawBackup, testPassword);
    await page.locator('#utilityModal .close[data-close]').click();
    await page.locator('#borrowerRows').getByRole('button', { name: 'Delete', exact: true }).click();
    await page.locator('#confirmModal').getByRole('button', { name: 'Cancel' }).click(); await visible(page.locator('#borrowerRows').getByText(name, { exact: true }));
    await page.locator('#borrowerRows').getByRole('button', { name: 'Delete', exact: true }).click(); await click('Delete borrower');
    await visible(page.getByText('No borrowers yet. Add your first borrower to begin.'));
    await click('Settings & backup'); await click('Undo last deletion'); await page.locator('#utilityModal .close[data-close]').click();
    await visible(page.locator('#borrowerRows').getByText(name, { exact: true }));
    await click('Settings & backup'); await page.locator('#restoreInput').setInputFiles(backupPath); await backupPassword(); await click('Restore backup'); await visible(page.getByText('Backup restored.', { exact: true })); await page.locator('#utilityModal .close[data-close]').click();
    await page.reload(); await unlock(); await visible(page.locator('#borrowerRows').getByText(name, { exact: true }));
    // Populate only this isolated test browser to verify pagination and multiple currencies.
    const payload = decryptedBackup.payload.portfolio;
    payload.loans = [...payload.loans, ...Array.from({ length: 10 }, (_, i) => ({ ...payload.loans[0], id: `extra-${i}`, name: `Borrower ${i}`, payments: {}, documents: [], currency: i === 9 ? 'CNY' : 'INR' }))];
    await injectPortfolio(payload);
    assert.equal(await page.locator('#borrowerRows tr').count(), 8); await click('Next page'); assert.equal(await page.locator('#borrowerRows tr').count(), 2); await click('Previous page');
    await page.locator('#sortSelect').selectOption('amount'); await page.locator('#sortSelect').selectOption('due');
    await page.locator('#currencySelect').selectOption('CNY'); assert.equal(await page.locator('#borrowerRows tr').count(), 1); await page.locator('#currencySelect').selectOption('INR');
    const beforeGlobalSearchTotal = await page.locator('#totalOutstanding').textContent();
    await page.locator('#searchInput').fill('Borrower 9'); await click('Search');
    await visible(page.locator('#borrowerRows').getByText('Borrower 9', { exact: true }));
    assert.equal(await page.locator('#currencySelect').inputValue(), 'INR');
    const yuanAmount = await page.evaluate(() => new Intl.NumberFormat(navigator.language, { style: 'currency', currency: 'CNY', minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(1800));
    assert.equal(await page.locator('#borrowerRows td[data-label=Loan] strong').textContent(), yuanAmount);
    assert.equal(await page.locator('#totalOutstanding').textContent(), beforeGlobalSearchTotal);
    assert.ok((await page.locator('#searchFeedbackText').textContent()).includes('Dashboard totals below remain in INR'));
    await page.screenshot({ path: path.join(out, 'search-desktop.png'), animations: 'disabled' });
    await page.locator('#searchInput').fill('Borrower'); await click('Next page');
    await page.locator('#searchInput').fill('Borrower 9'); assert.equal(await page.locator('#prevPage').isDisabled(), true);
    for (const width of [320, 390, 768, 1024]) {
      await page.setViewportSize({ width, height: 844 });
      await page.locator('#searchInput').fill('Borrower 9'); await click('Search');
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Search has no page overflow at ${width}px`);
      assert.ok(await page.locator('#borrowersTitle').evaluate(element => { const bounds = element.getBoundingClientRect(); return bounds.top >= 0 && bounds.bottom <= innerHeight; }), `Search results visible at ${width}px`);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('#searchInput').fill('Borrower 9'); await click('Search'); await page.screenshot({ path: path.join(out, 'search-mobile.png'), animations: 'disabled' });
    await page.locator('#searchInput').press('Escape'); assert.equal(await page.locator('#searchInput').inputValue(), '');
    await hidden(page.locator('#searchFeedback'));
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('link', { name: 'Borrowers', exact: false }).click(); await page.getByRole('link', { name: 'Overview', exact: true }).click(); await page.getByRole('link', { name: 'L Lendwise', exact: true }).click();
    await page.getByRole('button', { name: 'Repayments', exact: true }).click(); await page.locator('#paymentsModal .close[data-close]').click();
    await page.getByRole('button', { name: 'Reports', exact: true }).click(); await page.locator('#utilityModal .close[data-close]').click();
    await click('View all'); await page.locator('#paymentsModal .close[data-close]').click();
    await click('Manage backups'); await page.locator('#utilityModal .close[data-close]').click();
    await click('Settings & backup'); await page.locator('#motionToggle').uncheck();
    assert.equal(await page.locator('html').getAttribute('data-motion'), 'off');
    await page.locator('#motionToggle').check(); assert.equal(await page.locator('html').getAttribute('data-motion'), 'on');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.locator('html[data-motion="off"]').waitFor();
    assert.equal(await page.locator('html').getAttribute('data-motion'), 'off');
    assert.equal(await page.locator('#utilityModal').evaluate(element => getComputedStyle(element).animationName), 'none');
    await page.emulateMedia({ reducedMotion: 'no-preference' }); await page.locator('#utilityModal .close[data-close]').click();
    await page.screenshot({ path: path.join(out, 'dashboard-desktop.png'), fullPage: true, animations: 'disabled' });
    // Phone controls stay reachable, and dialogs have no clipped close/save buttons.
    await page.setViewportSize({ width: 390, height: 844 });
    await click('Toggle menu'); await visible(page.locator('#sidebar')); await click('Reports'); await page.locator('#utilityModal .close[data-close]').click();
    assert.equal(await page.locator('#menuBtn').getAttribute('aria-expanded'), 'false');
    await click('Toggle menu'); await click('Toggle menu');
    await page.locator('#newLoanTop').click(); await page.screenshot({ path: path.join(out, 'loan-mobile.png'), animations: 'disabled' });
    assert.ok(await page.locator('#saveLoan').evaluate(button => {
      const bounds = button.getBoundingClientRect(), modal = button.closest('dialog').getBoundingClientRect();
      return bounds.bottom <= modal.bottom && bounds.top >= modal.top && bounds.right <= modal.right;
    }), 'The entire save button fits inside the phone dialog');
    await page.locator('#loanModal [data-close]').first().click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.screenshot({ path: path.join(out, 'dashboard-mobile.png'), fullPage: true, animations: 'disabled' });
    for (const width of [320, 375, 768, 1024]) {
      await page.setViewportSize({ width, height: 900 });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal page overflow at ${width}px`);
    }
    // Clear receipt flow, document removal, invalid restore and storage failures.
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#searchInput').fill(name);
    await page.locator('#borrowerRows').getByRole('button', { name: 'Payments', exact: true }).click();
    await page.locator('#paymentRows tr').first().getByRole('button').click(); await page.locator('#receiptForm [name=amount]').fill('0'); await click('Save payment'); await click('Clear payment');
    await hidden(page.locator('#receiptModal')); assert.ok((await page.locator('#paymentRows tr').first().textContent()).includes('Overdue')); await page.locator('#paymentsModal .close[data-close]').click();
    await page.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).click(); await click('Remove'); await click('Save changes'); await hidden(page.locator('#loanModal'));
    await click('Documents'); await visible(page.getByText('No documents saved. Add them when creating or editing a borrower.')); await page.locator('#utilityModal .close[data-close]').click();
    await click('Settings & backup'); await page.locator('#restoreInput').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":3,"loans":[{}]}') });
    await visible(page.locator('#toast')); await page.locator('#utilityModal .close[data-close]').click();
    // Custom monthly repayment is independent of the principal and uses no APR.
    await page.locator('#searchInput').fill(''); await page.locator('#addBorrower').click();
    for (const [key, value] of Object.entries({ name: 'Custom monthly borrower', phone: '+86 123456789', amount: '1000', months: '3', firstDue })) await fields.locator(`[name="${key}"]`).fill(value);
    await fields.locator('[name=repaymentMode]').selectOption('custom'); await fields.locator('[name=payment]').fill('250');
    assert.equal(await fields.locator('[name=rate]').isDisabled(), true);
    assert.ok((await page.locator('#scheduleTotalPreview').textContent()).includes('750'));
    await click('Save borrower & loan'); await hidden(page.locator('#loanModal'));
    await page.locator('#searchInput').fill('Custom monthly borrower');
    await page.locator('#borrowerRows').getByRole('button', { name: 'Payments', exact: true }).click();
    assert.equal(await page.locator('#paymentRows tr').count(), 3);
    for (let i = 0; i < 3; i++) assert.ok((await page.locator('#paymentRows tr').nth(i).locator('td').nth(2).textContent()).includes('250'));
    await page.locator('#paymentsModal .close[data-close]').click();
    await page.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).click();
    assert.equal(await fields.locator('[name=repaymentMode]').inputValue(), 'custom');
    await fields.locator('[name=payment]').fill('275'); await click('Save changes'); await hidden(page.locator('#loanModal'));
    await page.reload(); await unlock();
    await page.locator('#searchInput').fill('Custom monthly borrower'); assert.ok((await page.locator('#borrowerRows').textContent()).includes('275'));
    // Sign-out clears rendered borrower details. Password changes preserve data.
    await click('Sign out & lock'); await hidden(page.locator('#appShell'));
    assert.equal((await page.locator('body').textContent()).includes('Custom monthly borrower'), false);
    await unlock(); await click('Settings & backup'); await click('Change password');
    await page.locator('#passwordForm [name=password]').fill(testPassword);
    await page.locator('#passwordForm [name=newPassword]').fill('New synthetic password 2026');
    await page.locator('#passwordForm [name=confirmPassword]').fill('New synthetic password 2026');
    await page.locator('#passwordForm').getByRole('button', { name: 'Continue' }).click();
    await visible(page.getByText('Password changed. Download a new encrypted backup. Older backups still use the old password.', { exact: true }));
    await page.locator('#utilityModal .close[data-close]').click(); await click('Sign out & lock');
    await page.locator('#authForm [name=password]').fill(testPassword); await page.locator('#authSubmit').click(); await visible(page.locator('#authError')); await hidden(page.locator('#appShell'));
    await unlock('New synthetic password 2026');
    // A different browser starts empty; encrypted backup + original password transfers the profile.
    const otherContext = await browser.newContext(); const otherPage = await otherContext.newPage(); await otherPage.goto(url);
    await visible(otherPage.getByRole('heading', { name: 'Create your local profile' }));
    await otherPage.locator('#authScreen details').evaluate(element => element.open = true);
    await otherPage.locator('#authRestore').setInputFiles(backupPath);
    await otherPage.locator('#passwordForm [name=password]').fill(testPassword); await otherPage.locator('#passwordForm').getByRole('button', { name: 'Continue' }).click();
    await otherPage.getByRole('button', { name: 'Restore profile', exact: true }).click();
    await visible(otherPage.locator('#appShell')); await otherPage.locator('#currencySelect').selectOption('INR');
    await visible(otherPage.locator('#borrowerRows').getByText(name, { exact: true })); await otherContext.close();
    // Corrupt vault is never replaced by an empty portfolio, and raw recovery still downloads.
    await page.evaluate(() => localStorage.setItem('lendwiseVaultV1', '{broken')); await page.reload();
    await page.locator('#authForm [name=password]').fill(testPassword); await page.locator('#authSubmit').click(); await visible(page.locator('#authError'));
    await page.locator('#authScreen details').evaluate(element => element.open = true);
    await download(() => click('Download encrypted recovery copy'), 'recovery.json');
    assert.equal(await fs.readFile(path.join(out, 'recovery.json'), 'utf8'), '{broken');
    await injectPortfolio(payload);
    await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
    await page.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).first().click(); await click('Save changes'); await visible(page.locator('#loanError')); assert.ok((await page.locator('#loanError').textContent()).includes('Unable to save'));
    assert.deepEqual(errors, []);
    assert.deepEqual(remoteRequests, []);
    // Old plaintext data remains intact after a failed migration, then moves into the encrypted vault.
    const migrationContext = await browser.newContext(), migrating = await migrationContext.newPage();
    migrating.on('pageerror', error => errors.push(error.message)); await migrating.clock.install({ time: new Date() }); await migrating.goto(url);
    const oldData = JSON.stringify(payload), oldLegacy = JSON.stringify([{ retained: 'old raw recovery copy' }]);
    await migrating.evaluate(([current, old]) => { localStorage.setItem('lendwisePortfolioV3', current); localStorage.setItem('lendwiseBorrowers', old); }, [oldData, oldLegacy]);
    await migrating.reload(); await visible(migrating.locator('#migrationNotice'));
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwisePortfolioV3')), oldData);
    const createMigrated = async () => {
      await migrating.locator('#authForm [name=profileName]').fill('Migrated profile');
      await migrating.locator('#authForm [name=password]').fill(testPassword); await migrating.locator('#authForm [name=confirmPassword]').fill(testPassword);
      await migrating.locator('#localConsentField input').check(); await migrating.locator('#authSubmit').click();
    };
    await migrating.evaluate(() => { window.originalSetItem = Storage.prototype.setItem; Storage.prototype.setItem = function(key, value) { if (key === 'lendwiseVaultV1') throw new DOMException('Quota', 'QuotaExceededError'); window.originalSetItem.call(this, key, value); }; });
    await createMigrated(); await visible(migrating.locator('#authError'));
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwisePortfolioV3')), oldData);
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), null);
    await migrating.evaluate(() => { Storage.prototype.setItem = window.originalSetItem; });
    await createMigrated(); await visible(migrating.locator('#appShell'));
    assert.deepEqual(await migrating.evaluate(() => ['lendwisePortfolioV3', 'lendwiseBorrowers'].map(key => localStorage.getItem(key))), [null, null]);
    const migratedVault = await V.unlock(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), testPassword);
    assert.equal(migratedVault.payload.portfolio.loans.length, payload.loans.length);
    assert.equal(migratedVault.payload.legacyRecovery.lendwisePortfolioV3, oldData);
    assert.equal(migratedVault.payload.legacyRecovery.lendwiseBorrowers, oldLegacy);
    // Removing recovery copies never changes active borrower records.
    await migrating.getByRole('button', { name: 'Settings & backup', exact: true }).click();
    await migrating.getByRole('button', { name: 'Remove old migration copies', exact: true }).click();
    await migrating.locator('#confirmModal').getByRole('button', { name: 'Cancel', exact: true }).click();
    assert.equal((await V.unlock(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), testPassword)).payload.legacyRecovery.lendwiseBorrowers, oldLegacy);
    await migrating.getByRole('button', { name: 'Remove old migration copies', exact: true }).click();
    await migrating.getByRole('button', { name: 'Remove old copies', exact: true }).click();
    await visible(migrating.getByText('No old migration copies are retained in this profile.', { exact: true }));
    const afterPurge = (await V.unlock(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), testPassword)).payload;
    assert.equal(afterPurge.legacyRecovery, undefined); assert.deepEqual(afterPurge.portfolio, migratedVault.payload.portfolio);
    await migrating.locator('#utilityModal .close[data-close]').click();
    // A write in a second tab invalidates the first unlocked view, not just its next save.
    const secondTab = await migrationContext.newPage(); await secondTab.goto(url);
    await secondTab.locator('#authForm [name=password]').fill(testPassword); await secondTab.locator('#authSubmit').click(); await visible(secondTab.locator('#appShell'));
    await migrating.locator('#currencySelect').selectOption('INR');
    await migrating.locator('#borrowerRows').getByRole('button', { name: 'Edit', exact: true }).first().click();
    await migrating.locator('#loanForm [name=name]').fill('Changed from another tab'); await migrating.getByRole('button', { name: 'Save changes', exact: true }).click();
    await hidden(migrating.locator('#loanModal')); await hidden(secondTab.locator('#appShell'));
    assert.ok((await secondTab.locator('#authError').textContent()).includes('another tab'));
    await secondTab.close();
    await migrating.locator('#borrowerRows [data-action=score]').first().click(); await visible(migrating.locator('#scoreModal'));
    // Idle lock scrubs the visible data, closes dialogs and keeps ciphertext intact.
    const beforeIdle = await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1'));
    await migrating.clock.fastForward(301000);
    await hidden(migrating.locator('#appShell'));
    await hidden(migrating.locator('#scoreModal')); assert.equal(await migrating.locator('#scoreInstallments').textContent(), '');
    assert.equal(await migrating.locator('#searchInput').inputValue(), ''); assert.equal(await migrating.locator('#searchFeedbackText').textContent(), '');
    assert.equal((await migrating.locator('body').textContent()).includes('Changed from another tab'), false);
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), beforeIdle);
    await migrating.setViewportSize({ width: 390, height: 844 });
    await migrating.screenshot({ path: path.join(out, 'local-profile-mobile.png'), fullPage: true, animations: 'disabled' });
    assert.ok(await migrating.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    // Profile deletion is password-confirmed, cancelable, and scoped to only Lendwise keys.
    await migrating.setViewportSize({ width: 1440, height: 1000 });
    await migrating.locator('#authForm [name=password]').fill(testPassword); await migrating.locator('#authSubmit').click(); await visible(migrating.locator('#appShell'));
    await migrating.evaluate(() => localStorage.setItem('unrelated-project-key', 'keep me'));
    const beforeDelete = await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1'));
    await migrating.getByRole('button', { name: 'Settings & backup', exact: true }).click(); await migrating.getByRole('button', { name: 'Delete local profile', exact: true }).click();
    await migrating.locator('#passwordForm [name=password]').fill('Wrong password'); await migrating.locator('#passwordForm').getByRole('button', { name: 'Continue' }).click();
    await visible(migrating.getByText('Incorrect password, or the encrypted data is damaged. Nothing has been changed.', { exact: true }));
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), beforeDelete);
    const requestDelete = async () => {
      await migrating.getByRole('button', { name: 'Delete local profile', exact: true }).click();
      await migrating.locator('#passwordForm [name=password]').fill(testPassword); await migrating.locator('#passwordForm').getByRole('button', { name: 'Continue' }).click();
      await visible(migrating.getByRole('heading', { name: 'Permanently delete this local profile?' }));
    };
    await requestDelete(); await migrating.locator('#confirmModal').getByRole('button', { name: 'Cancel', exact: true }).click();
    assert.equal(await migrating.evaluate(() => localStorage.getItem('lendwiseVaultV1')), beforeDelete);
    await requestDelete(); await migrating.getByRole('button', { name: 'Delete profile permanently', exact: true }).click(); await hidden(migrating.locator('#appShell'));
    assert.deepEqual(await migrating.evaluate(() => ['lendwiseVaultV1', 'lendwisePortfolioV3', 'lendwiseBorrowers', 'lendwiseCurrency', 'lendwiseMotion'].map(key => localStorage.getItem(key))), [null, null, null, null, null]);
    assert.equal(await migrating.evaluate(() => localStorage.getItem('unrelated-project-key')), 'keep me');
    await visible(migrating.getByRole('heading', { name: 'Create your local profile', exact: true }));
    await migrationContext.close(); assert.deepEqual(errors, []);
    console.log('PASS: local profiles, encryption, wrong-password rejection, lock/reload, password change, encrypted restore, migration/copy removal, scoped profile deletion, custom dues, borrower CRUD, receipts/filters, progress bars, score breakdown/live edits/exports/lock scrubbing, currency integrity, navigation, close/cancel/discard, search/filter/sort/pages, documents, CSV/XLSX, corruption/quota handling, 320–1440px layouts, reduced motion, no browser errors or off-origin requests in monitored flows.');
  } finally { await browser.close(); server.close(); }
}
main().catch(error => { console.error(error); server.close(); process.exitCode = 1; });

